### ISSUE TITLE
Add option to enable commit signing

### ISSUE THREAD

**Issue by jacklesliewise** [changesets/action#126]
# Context

At the moment, if you use this action and have the `Require signed commits` setting enabled for a protected branch, the PR generated can't be merged.

# Example

[Crowdin](https://crowdin.com/), a popular localisation management tool, has a similar [action](https://github.com/crowdin/github-action) which opens a PR using a bot.

They allow you to pass a `gpg_private_key` as a config option, which will enable signed commits for the bot opening the PR. See options [here](https://github.com/crowdin/github-action#supported-options).

**Comment by Andarist** [comment]
Sure, if you want to implement this - I would gladly review and merge a PR for this. For reference - this is what they do based on the `gpg_private_key` input:
https://github.com/crowdin/github-action/blob/b9b3c18f523d40926d75e48fc7fd2b6fdc23caee/entrypoint.sh#L174-L193

**Comment by jacklesliewise** [comment]
@Andarist opened a PR, let me know what you think!
