### ISSUE TITLE
How to configure this action when project is not in the root folder?

### ISSUE THREAD

**Issue by dmregister** [changesets/action#133]
The project using changeset is currently in a sub-directory and the action is failing due to `process.cwd` not being in the correct folder. Is there a way to configure this for this action?

**Comment by Andarist** [comment]
I'm pretty sure that using our `version` and `publish` inputs with a script changing the working directory and invoking the appropriate Changesets command would do the trick.

We potentially could also support a new `cwd` input if you'd like to implement such a feature - this didn't come up until now.

**Comment by dmregister** [comment]
@Andarist I was able to get this working. The issue with using cd in the version script, is in the index.ts it calls `readChangesetState`, which uses `process.cwd` so it's before the version cmd. Changing the directory just for the node process also allows all the other default params using `process.cwd()` to be in the correct dir was well.

I was hoping to write a test for this, but it seems there isn't anything setup for index.ts (without mocking everything). Is that correct?

**Comment by gyurielf** [comment]
> @Andarist I was able to get this working. The issue with using cd in the version script, is in the index.ts it calls `readChangesetState`, which uses `process.cwd` so it's before the version cmd. Changing the directory just for the node process also allows all the other default params using `process.cwd()` to be in the correct dir was well.
> 
> I was hoping to write a test for this, but it seems there isn't anything setup for index.ts (without mocking everything). Is that correct?

Nice!
It's a game changer feature! :)

**Comment by dmregister** [comment]
@gyurielf i've updated the README, is there something else that should be added as well?

**Comment by gyurielf** [comment]
I think it's should be fine.

It would be nice if somebody can merge it.

**Comment by Andarist** [comment]
I believe that this has been addressed by https://github.com/changesets/action/pull/134

**Comment by gyurielf** [comment]
> I believe that this has been addressed by #134

Cheers!
