### ISSUE TITLE
Bug: Changeset file with empty content will fail

### ISSUE THREAD

**Issue by akphi** [changesets/action#138]
If I have these 2 changeset files

File 1

```
---
"a": patch
---
```

File 2

```
---
"a": patch
---

```

File 1 will fail the pipeline while file 2 will not - See this example

https://github.com/finos/legend-studio/runs/4899417130?check_suite_focus=true

---

I can help look at a fix for this issue, but please let me know if this is intended or if you would treat this as a bug and willing to let me work on it. Thanks!

**Comment by Andarist** [comment]
I would classify this as a bug - the fix would involve adjusting this regex:
https://github.com/changesets/changesets/blob/c68536edf4c04e7fdf5594ec9c69471cd86fd0ce/packages/parse/src/index.ts#L4

If you could work on that - that would be splendid. Remember that a PR like this should come with a test covering the changes.
