### ISSUE TITLE
Creation of .netrc issue might fail the action if not gitignored

### ISSUE THREAD

**Issue by belgattitude** [changesets/action#148]
Minor issue, the new 1.2.0 version creates a .netrc file. This makes the action fail (was working on 1.1.0)

![image](https://user-images.githubusercontent.com/259798/152825988-462f3a8f-ee9a-4b95-abe7-3f804d40c9e9.png)

## How to solve

Just add `.netrc` in .gitignore.

**Comment by belgattitude** [comment]
Left a note here: https://github.com/changesets/action/issues/148

**Comment by Andarist** [comment]
Note that this file was always created by this action - the code lines writing to this file are part of the initial commit:
https://github.com/changesets/action/commit/1278d96a467b91be8d39232948bd2fa88eb57434#diff-dcdc3e0b3362edb8fec2a51d3fa51f8fb8af8f70247e06d9887fa934834c9122R72-R75

**Comment by belgattitude** [comment]
Thx, I'll dig deeper. At least seems to work now.
