### ISSUE TITLE
Release changelog not published to GitHub Releases

### ISSUE THREAD

**Issue by eegli** [changesets/action#153]
I am not sure whether this is issue belongs here or to `@changesets/changelog-git` / `@changesets/changelog-github`. Afaik, this action is ultimately responsible for creating GitHub release changelogs.

What I want to achieve is an automatic GitHub release changelog like https://github.com/changesets/action/releases/tag/v1.2.0 whenever a `Version release` PR is merged.

I've set up the bot and followed all the steps. My .changeset config includes ` "changelog": "@changesets/changelog-git"`.

When I get the release PR and merge it, the packages are correctly published to NPM but there is no release changelog on GitHub. Is this only available for organisational repos? I'm in a user repo.

Thanks for the help.

**Comment by eegli** [comment]
Alright, after explicitly passing

```yml
with:
  createGithubReleases: true
```

(and the other stuff), it seems to work! A little weird to me since the `action.yml` file says that this should be true by default. But I'm not quite familiar with the way GH actions are developed and how defaults are considered.

**Comment by Andarist** [comment]
Hmm, that is super weird. I've just released XState: https://github.com/statelyai/xstate/releases/tag/xstate%404.30.3 and I definitely don't have this flag explicitly set:
https://github.com/statelyai/xstate/blob/a40b5034509ed9838d50111af734b468c871d977/.github/workflows/release.yml#L21-L28

**Comment by eegli** [comment]
Upon further investigation, I think the problem was not related to changesets but rather version conflicts on NPM when publishing after I had migrated some packages into a monorepo. Anyway, it does not seem to be a problem anymore. I'll remove the explicit `createGithubReleases` at some point and will check again.

Thanks for the help!
