### ISSUE TITLE
`node_modules/.bin/eslint` added to git during release workflow

### ISSUE THREAD

**Issue by melanieseltzer** [changesets/action#160]
Related to https://github.com/changesets/action/issues/146

I am also experiencing the issue but with `node_modules/.bin/eslint` symlinks. 

You can see that they are [getting added here in my version PR](https://github.com/melanieseltzer/toolkit/pull/17/files#diff-63ee40f05dd2398ee1d5c6e14a34f6e6cca888610733116255a70d25b0bde5b3). The `yarn install` generates them, and then they get added to version control even though [node_modules is blanket ignored in my .gitignore file](https://github.com/melanieseltzer/toolkit/blob/main/.gitignore#L9). In fact, if I do `git status --ignored` it shows the outer `node_modules` are in fact, ignored.

<img width="659" alt="Screen Shot 2022-03-10 at 8 42 07 AM" src="https://user-images.githubusercontent.com/17421347/157711914-2e4abdd4-69bd-4c0c-8c38-30fa0380efd8.png">

 But just the symlinks inside the ignored `node_modules` are getting added during the workflow run 🤔

<img width="667" alt="Screen Shot 2022-03-09 at 5 22 19 PM" src="https://user-images.githubusercontent.com/17421347/157568446-4f53520d-480b-45a3-8b64-4ee57e82f9ea.png">

**Comment by Andarist** [comment]
That is strange. Have you tried to replicate those steps locally in an empty repo? This could give us more info about the git behavior around this and perhaps could point us to the answer

**Comment by melanieseltzer** [comment]
Yes, locally it seems fine, git seems to respect the `.gitignore` at least. For instance, I've got a branch that adds a new package to my monorepo called `eslint-config-prettier` and you can see here that locally the `node_modules` is ignored as it's supposed to be:

<img width="508" alt="Screen Shot 2022-03-18 at 8 19 31 PM" src="https://user-images.githubusercontent.com/17421347/159104761-91a8190b-ee25-4e03-8c8a-cc612219a822.png">

`git status --ignored` shows it is indeed ignored, and `node_modules` isn't there in the list when doing a `git add . --dry-run`. Seems like the action is just not respecting the `.gitignore` when at the `git add` step in CI 🤔 

Off the top of my head, is `--force` getting appended to the add command somewhere in the action? That would allow adding of otherwise ignored files. But I guess that would show in my screenshot, so maybe not...

**Comment by Andarist** [comment]
> Off the top of my head, is --force getting appended to the add command somewhere in the action? That would allow adding of otherwise ignored files.

This was what popped into my head when you have opened this issue but I've rechecked and we don't use this anywhere when git adding files.

Unfortunately, I'm a little out of ideas here. Could you perhaps add me temporarily as a collaborator to your project? I could then experiment with this action on a separate throwaway branch.

**Comment by Andarist** [comment]
Could you also perhaps try replacing [this line](https://github.com/melanieseltzer/toolkit/blob/8b438a1eed6515c5b628f660d4969412c8f68b69/.gitignore#L9) like this?
```diff
-/node_modules
+node_modules
```

**Comment by melanieseltzer** [comment]
For those who may come across this - the problem was indeed the leading `/`, it should be `node_modules` not `/node_modules` in the `.gitignore` (to ignore `node_modules` at all levels, not just at the same level as the `.gitignore` file). 

The problem was being obscured to me locally because I had a `.gitignore_global` with the correct `node_modules` line, so the problem was only showing up in the CI run, making me think it was related to this GitHub Action. 

@Andarist's PR has a nice explanation: https://github.com/melanieseltzer/toolkit/pull/20 Thanks again!
