### ISSUE TITLE
body is too long (maximum is 65536 characters)

### ISSUE THREAD

**Issue by bennypowers** [changesets/action#174]
If changesets are long, github API will throw `body is too long (maximum is 65536 characters)`, e.g. [this run](https://github.com/patternfly/patternfly-elements/runs/6028590519?check_suite_focus=true)

changesets action could truncate the message or something.

This is likely to happen when a changeset is medium-long and there are many packages in the monorepo

**Comment by Andarist** [comment]
This will get fixed by https://github.com/changesets/action/pull/157
