### ISSUE TITLE
Custom changelog config error

### ISSUE THREAD

**Issue by jmd01** [changesets/action#176]
I have added
`  "changelog": ".changeset/changelog-config.js",` to my `config.json` file: https://github.com/jmd01/changesets/blob/main/.changeset/config.json

And created the file at that path:
https://github.com/jmd01/changesets/blob/main/.changeset/changelog-config.js

But on running the action I get an error:
`/home/runner/work/changesets/changesets/node_modules/@changesets/cli/bin.js version
Cannot find module '.changeset/changelog-config.js'`
https://github.com/jmd01/changesets/runs/6190603574?check_suite_focus=true

Am I missing something?

**Comment by mitchellhamilton** [comment]
The changelog generator is resolved relative to the config file, not the root of the repo so you should set `"changelog": "./changelog-config.js"`

**Comment by jmd01** [comment]
Thanks!
