### ISSUE TITLE
What is email in .npmrc?

### ISSUE THREAD

**Issue by pmcelhaney** [changesets/action#185]
Per the README:

> However, if a `.npmrc` file is found, the GitHub Action does not recreate the file. This is useful if you need to configure the `.npmrc` file on your own. For example, you can add a step before running the Changesets GitHub Action:
>
> ```yml
> - name: Creating .npmrc
>   run: |
>    cat << EOF > "$HOME/.npmrc"
>       email=my@email.com
>      //registry.npmjs.org/:_authToken=$NPM_TOKEN
>     EOF
>   env:
>     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
>  ```

What exactly does `email=my@email.com` do? Is that a real field in `.npmrc`? If not, can we delete that line from the README?

**Comment by Andarist** [comment]
I honestly don't know 😅 I think it can be removed. Would you mind preparing a PR for that?

**Comment by pmcelhaney** [comment]
Done! 

Another question: is it necessary to add an `NPM_TOKEN` secret to Github? By default I think the token automatically created and stored in `secrets.GITHUB_TOKEN` has the necessary permissions. This seems to work.

```yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }} # instead of secrets.NPM_TOKEN
```

**Comment by pmcelhaney** [comment]
🤦🏼  yeah that makes sense. It works for me because I'm publishing to Github.

**Comment by cyrfer** [comment]
I'm also trying to publish a private repo to a private github packages repository. I'm trying to use this action but it's confusing me.

**Comment by pmcelhaney** [comment]
@cyrfer What’s confusing? I’m happy to help if you share more detail. Email me at pmcelhaney@gmail.com if you prefer.

**Comment by cyrfer** [comment]
@pmcelhaney email sent. Thanks for the offer. I'm confused about how to publish to github package registry.
