### ISSUE TITLE
Error: Have you forgotten to install `@changesets/cli` in "/home/runner/work/<package>/<package>"?

### ISSUE THREAD

**Issue by alexandra-c** [changesets/action#189]
Hello,

I'm trying to configure Changesets Release Action in a mono repo yarn berry pnp library and I'm facing the following issue:
https://github.com/osstotalsoft/rocket-toolkit/runs/6833425744?check_suite_focus=true
![image](https://user-images.githubusercontent.com/46926675/173096623-24982d85-da54-4945-a07a-72ceca307b4e.png)

This is how my workflow config looks like: https://github.com/osstotalsoft/rocket-toolkit/blob/main/.github/workflows/npm-publish.yml

Thanks! :)

**Comment by Andarist** [comment]
Have you tried [this](https://github.com/changesets/action/tree/6a46d2c28377497e64763ba5f1faeabbd3d88c33#with-yarn-2--plugnplay)?

**Comment by alexandra-c** [comment]
Yes, that worked. I'm still struggling now to bypass the branch restrictions for github-actions bot so it can automatically increase the version and publish in one step. 
I guess this issue can be closed now.
Thank you! 🙌

**Comment by Andarist** [comment]
> I'm still struggling now to bypass the branch restrictions for github-actions bot so it can automatically increase the version and publish in one step.


I would need more information to help out with that.

**Comment by alexandra-c** [comment]
I need to do both changeset version and publish in one workflow run. 
This is my workflow config: https://github.com/osstotalsoft/rocket-toolkit/blob/main/.github/workflows/npm-publish.yml#:~:text=changesets/action%40v1-,with%3A,publish%3A%20yarn%20release,-env%3A
Right now, if there are any new changests, it generates a PR to update the version, someone needs to approve and merge it, and then run the pipeline again to do the publish. 
Can this be done in only one run? So it automatically bypasses all branch policies and commits the version updates without any PR and then publishes the library?

**Comment by Andarist** [comment]
On such an occasion, it would be best **not** use this action. Just `changeset version && changeset publish` in a custom workflow. Just be wary of potential race conditions etc (multiple branches with changesets can be merged to your main branch roughly at the same time) - you might look into the `concurrency` option for GitHub workflows, maybe it could help a little bit with that.
