### ISSUE TITLE
Getting error without description when publishing

### ISSUE THREAD

**Issue by gfellerph** [changesets/action#191]
Hi there,

I've set up the pnpm publish action for the first time in a new project and I'm getting an error when publishing but no error message.

https://github.com/swisspost/common-web-frontend/runs/6937268572?check_suite_focus=true#step:7:157

The first library is able to publish just fine, but the second fails. I'm not sure if the issue is related to the changesets action, github or npm, would it be possible to improve the error message?

**Comment by Andarist** [comment]
I'm pretty confident that I've located the correct place in the code by which this was logged. I've prepared a PR to improve this situation - but without actually knowing what is happening in your case this fix is just a shot in the dark: https://github.com/changesets/changesets/pull/844/files

**Comment by gamertike** [comment]
> I ran into the same issue, the fix was removing `directory` from `publishConfig` from the package.json. Looks to be the same fix as [swisspost/common-web-frontend#152](https://github.com/swisspost/common-web-frontend/pull/152)

i dont even have a`publishConfig` and im getting the same error

**Comment by gamertike** [comment]
[failed run](https://github.com/guildedts/guilded.ts/runs/7469778801?check_suite_focus=true)
[release.yml](https://github.com/guildedts/guilded.ts/blob/main/.github/workflows/release.yml)

**Comment by gamertike** [comment]
any other solutions?
