### ISSUE TITLE
If all changesets are empty, the action still creates a PR

### ISSUE THREAD

**Issue by glasser** [changesets/action#205]
If the only changesets on the branch are "empty" changesets (like those created with `changeset --empty`, perhaps to make a `changeset status` CI check pass), the action will still create a PR with no releases. That seems unnecessary? I think it's reasonable that `changeset version` won't be a no-op in this case (deleting the changeset files or adding them to the list in `pre.json`) but creating a PR seems overkill?

**Comment by Andarist** [comment]
Yeah, this makes sense - we should skip creating the PR in such a case. I would happily accept a PR fixing this.

**Comment by kachkaev** [comment]
What about cases when changests are empty but dependencies got an update? I’d expect the PR to be up in this scenario.

**Comment by glasser** [comment]
@kachkaev I'm not sure exactly what you mean here (wouldn't there need to be some changeset somewhere in order for there to be a release in the PR?) but I definitely could have missed something as a non-expert.
