### ISSUE TITLE
Is it possible to use this action for private registries? I.e.: Nexus

### ISSUE THREAD

**Issue by tcK1** [changesets/action#217]
I've been trying to make it work but had no success, is there any examples of how to do it? 😅

One thing to note is that I'm using the legacy auth (`_auth=`).

List of things I've tried:

- Custom `.npmrc` at `$HOME` with the `email` and `_auth` variables.
- Custom `.npmrc` at `$HOME` with the `email` and `_auth` and `registry` variables.
- Custom `.npmrc` at the package being published with the `email` and `_auth` variables.
- Custom `.npmrc` at the package being published with the `email` and `_auth` and `registry` variables.
- I manually deleted the generated `.npmrc` and combined it with the others `.npmrc`s I created manually.

Edit.: I've also tried with the `_authToken` but with no success. 🥲

**Comment by tcK1** [comment]
I was able to make it work with the following configurations on my `$HOME/.npmrc`:

```
registry=https://my-registry/repository/npm-group/

@scope:registry=https://my-registry/repository/npm-hosted/
//my-registry/repository/npm-hosted/:username=$NEXUS_USER
//my-registry/repository/npm-hosted/:_password=$(echo -n $NEXUS_PASS | base64)
```

**Comment by VladSez** [comment]
Hi @tcK1, could you, please, share the workflow that worked for you?
