### ISSUE TITLE
Setting GitHub credentials unnecessary?

### ISSUE THREAD

**Issue by jedrichards** [changesets/action#22]
Looks like the latest version of the [`actions/checkout`](https://github.com/actions/checkout) action persists the GitHub credentials automatically, for usage by future job steps:

> The auth token is persisted in the local git config. This enables your scripts to run authenticated git commands. The token is removed during post-job cleanup. Set persist-credentials: false to opt-out.

So was wondering whether these parts of your code are superfluous now?

https://github.com/changesets/action/blob/master/index.ts#L32-L50

**Comment by JakeGinnivan** [comment]
I am using a PAT for auth instead of the actions token because the actions token prevents further workflow actions to trigger (ie a build for the changeset branch).

For this reason I think it should stay explicit

**Comment by jedrichards** [comment]
I think I discovered the PAT use case too, since writing this issue. You're correct, I'll close this one 👍
