### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by orgroman** [changesets/action#221]
I would like to fork the project and extend it and yarn changesets for **python poetry**.
Could you add a license to the repo? thanks

**Comment by Andarist** [comment]
The license is already specified [here](https://github.com/changesets/action/blob/398d7edfb130ad2d4e076a573724f435ea87cea6/package.json#L5). Why do we also have to provide the text of the **standard** license in the repro itself?

**Comment by orgroman** [comment]
> The license is already specified [here](https://github.com/changesets/action/blob/398d7edfb130ad2d4e076a573724f435ea87cea6/package.json#L5). Why do we also have to provide the text of the **standard** license in the repro itself?

Thanks! missed it, more than enough

**Comment by martincostello** [comment]
Adding a license file to the repo would populate the `license` property [of the repo in the GitHub API](https://api.github.com/repos/changesets/action) and allow automated tooling to easily find out how it is licensed.

```
"license": null
```

It currently appears as null, and then all the associated top-level UI in GitHub itself to show the licensing isn't shown. Having to dig through the repository to find out how it's licensed isn't ideal.

If it was easy to find, the original posted probably would never have even opened this issue in the first place as they would have found it.
