### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by unional** [changesets/action#222]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: changesets/action

**Comment by kachkaev** [comment]
Same problem here:

This should be fixed by https://github.com/changesets/action/pull/154. It'd be great to see it merged 🙏
