### ISSUE TITLE
Gots 404 error on npm when publishing with GitHub Actions

### ISSUE THREAD

**Issue by EduardoJM** [changesets/action#311]
I have a monorepo with some packages and i decided to use `turbo` to manage the packages and the `changesets` to make publish a little more easy.

When the `changeset publish` is run in local repository, the packages are published to npm.

When i added the Github Actions to publish, i got an 404 error on PUT:

```
🦋  info npm info @inventare/icons
🦋  info npm info @inventare/react
🦋  info npm info @inventare/styles
🦋  warn @inventare/icons is not being published because version 0.0.1 is already published on npm
🦋  warn @inventare/react is not being published because version 0.0.9 is already published on npm
🦋  info @inventare/styles is being published because our local version (0.0.8) has not been published on npm
🦋  info Publishing "@inventare/styles" at "0.0.8"
🦋  error an error occurred while publishing @inventare/styles: E404 Not Found - PUT https://registry.npmjs.org/@inventare%2fstyles - Not found 
```

---

I viewed some other issues with related problems but i don't see any solution.

---

My repository: https://github.com/inventare/design-system
Complete log of action run: https://github.com/inventare/design-system/actions/runs/5581849500/jobs/10200447919

**Comment by axetroy** [comment]
Same with me.

Complete log of action run: https://github.com/axetroy/iconfont-componentized/actions/runs/5763320547/job/15624927029

**Comment by EduardoJM** [comment]
> Same with me.

I see new actions running on your repository:

![image](https://github.com/changesets/action/assets/20397491/8690f5bf-d742-4923-8d65-94716f4db476)

---

Found an solution for this problem?

**Comment by EduardoJM** [comment]
# Solution (for my case):

Add `NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}` env variable on action:

https://github.com/inventare/design-system/blob/main/.github/workflows/publish-to-npm.yml#L36C11-L36C52

**Comment by axetroy** [comment]
> Found an solution for this problem?

sorry, I didn't known how to resolve it. But I know it might be a problem with NPM token or NPM registry. so I tried various methods.

Glad you solved it. :)

**Comment by wamra** [comment]
The `actions/setup-node` action is designed to securely handle authentication tokens without exposing them in plaintext in the .npmrc file. When you provide a token to actions/setup-node, it intentionally writes the .npmrc file with the `_authToken set to ${NODE_AUTH_TOKEN}` as a placeholder. 

This means you need to set the `NODE_AUTH_TOKEN` environment variable in your workflow steps that require npm authentication.

Difference Between `NODE_AUTH_TOKEN` and `NPM_TOKEN`:
- `NODE_AUTH_TOKEN`: Officially recognized by npm as an environment variable for authentication.
- `NPM_TOKEN`: Not natively recognized by npm; often used as a custom variable name in scripts but requires additional configuration to be used by npm.
