### ISSUE TITLE
Incompatible with @changesets/cli v2.8.0

### ISSUE THREAD

**Issue by ocavue** [changesets/action#33]
In [@changesets/cli v2.8.0](https://github.com/atlassian/changesets/commit/5dc389f9cc03a59ef44f34243efe8ad00e35d465#diff-268d4deba624b8bba84127cce7721fcdR79-R86), the git tag format for single-package repositories has changed, which make [this regular expression](https://github.com/changesets/action/blob/6f5135b203d5101ecf2ef3eea53c5cc8bfad56c6/index.ts#L110) not longer working.

This causes two problems when using changesets/action with a single-package repositorie:

1. Can not create GitHub Release automatically.
2. The outputs (`published` and `publishedPackages`) from the Action don't contain correct package information.

**Comment by ocavue** [comment]
cc @Andarist

**Comment by Andarist** [comment]
Thanks for raising this! I'll try to fix this asap.

**Comment by Andarist** [comment]
Sorry for the delay - but I have good news. There is a pending PR to fix this: https://github.com/changesets/action/pull/35 - we should be able to merge & release it soon.
