### ISSUE TITLE
Preview release notes when changesets are added to the PR

### ISSUE THREAD

**Issue by TheUnderScorer** [changesets/action#403]
Hey folks!
Thanks for this great package and GitHub action, we use it in a bunch of our projects, and it greatly simplifies our release pipeline.

I wanted to discuss adding a new feature to this action. Currently, when you add a new changeset to the PR, following comment is added to it:
![Screenshot 2024-09-19 at 14 25 24](https://github.com/user-attachments/assets/d1138419-fa4e-4c8a-a848-475e867c8733)

I believe it would be also useful to include release notes that will be generated using these changesets, as it takes place in PR that is created after running `changeset version`:
![image](https://github.com/user-attachments/assets/67298d7d-d750-4939-82a1-5ad9231bac5c)

Of course, it doesn't have to be mandatory. There can be a flag that would determine whether this preview should be generated or not.

What do you think? If you accept external contributions, I'm more than happy to implement this, but I wanted to start the discussion first 🙂

Cheers!

**Comment by TheUnderScorer** [comment]
Sorry, I just realized that I've opened this issue in wrong repo. I'm going to close this one.

**Comment by yamcodes** [comment]
Here is the new location for the issue:
https://github.com/changesets/bot/issues/88
