### ISSUE TITLE
Integrated deployments

### ISSUE THREAD

**Issue by mark-omarov** [changesets/action#56]
Hi everyone 👋 

I'm curious if somebody could give me advice on how to configure the action with the deployment process.
The current process is simple. Every time on a push to master `changesets/action` creates/updates the PR, and when the PR merged, the packages are published to GPR.
However, the desired process is to have two deployments to DO:
The first deployment should be with the first step of the `changesets/action` - when PR is created, it deploys the particular changes to DO staging. I guess I could achieve it by creating a new workflow for the automatically generated PR.
The second one should deploy to DO production after `changesets/action`'s PR is merged, and packages are published.

I'm not sure if it's the right approach in general. I'd like to hear if that's possible to achieve with the action, and any advice is welcome.

**Comment by tompahoward** [comment]
Hi @mark-omarov , i get that this isn't on the roadmap, but are you saying that changesets doesn't need anything additional to support deployments, or are you saying we need to find another tool if we want to version deployables?

**Comment by mark-omarov** [comment]
Hey @tompahoward,
No need to look for another tool! Changesets Action is pretty flexible and you can totally customize it to fit your deployment needs. You can run custom scripts and make use of the outputs it gives to chain into your next GitHub Actions steps.

So you could easily set up a workflow similar to what I've described in the description.

Hope this helps!
