### ISSUE TITLE
Strange failures, not sure how to recover

### ISSUE THREAD

**Issue by pngwn** [changesets/action#60]
A short while ago the action failed to make the PR as it is supposed to due to the following error:

```
nothing to commit, working tree clean
Error: The process '/usr/bin/git' failed with exit code 1
Error: The process '/usr/bin/git' failed with exit code 1
```
[The CI run in question](https://github.com/pngwn/MDsveX/runs/1375793906?check_suite_focus=true)

I did have changeset files for this run (they are still there in master).

Now whenever I merge to master which runs the `release` steps that should generate a new PR, it fails in the same manner. I don't really know if it is the same issue I had originally or if I am stuck in a loop due to the original failure. 

Any idea what could be causing this?

**Comment by Andarist** [comment]
Im afraid that it doesnt give us a lot of info to work with. It would be great if u could try to debug on which command it fails - maybe that would shed a little bit more light on your case as your setup doesnt look anything different from the standard setup that a lot of other projects use without much of a problem 🤔

**Comment by pngwn** [comment]
Yeah, I sadly wasn't getting a great deal of info but I think I have figured it out. 

I had `commit: true` in my config file which actually explains why the working tree was clean when commiting _after_ running the version script. I'm not sure if this is a required setting when using the action but it seems to have solved my problem here. If it is required it may be worth documenting (which I'm happy to do if you point me), but it could be some funkiness around my setup also, I am using pnpm which complicates things a touch.

**Comment by Andarist** [comment]
I have actually forked your repo in the meantime and tried to play with it a little bit but didn't have any noteworthy results 😅 It's great that you have figured this out! I would have not guessed that git returns 1 when trying to commit on the clean working tree - the message itself doesn't sound like an error or anything. I've somewhat confirmed that this was probably the culprit by trying to execute:
```js
require('@actions/exec').exec("git", ["commit" ,"-m", "test"])
```
which results in the very same error you have encountered.

I believe this is an oversight on our part - this should be handled more gracefully. Could you report this to https://github.com/changesets/action ?

**Comment by pngwn** [comment]
Sure thing. Thanks for looking into this!

**Comment by pngwn** [comment]
Hold on, isn't that where I am now?

**Comment by Andarist** [comment]
Omg, I was somehow sure this thread was in the main Changeset repo. My bad 😅
