### ISSUE TITLE
Pre-releases

### ISSUE THREAD

**Issue by pngwn** [changesets/action#69]
Would it be possible to support pre-releases via this action, or is this already possible?

I know pre-releases are pretty complex with `changesets` but I wondered if the process could be simplified somewhat, I guess a string branching-naming strategy would be required to make it remotely reasonable.

I had a look for existing issues but I could not find anything. Is this something you would be interesting in supporting or is it already possible or perhaps too difficult?

**Comment by Andarist** [comment]
Prereleases are already supported:
1. create a new branch for your prerelease development
2. run `changeset pre enter` & adjust your release workflow file to run on your prerelease branch
3. branch of that, create changesets, merge to your prerelease branch
4. have releasing PRs generated for your prerelease branch 🎉 

You can take a look for an example branch created using this way here: https://github.com/davidkpiano/xstate/pull/902

**Comment by pngwn** [comment]
That's awesome thank you and thanks for the example link!
