### ISSUE TITLE
Include pull request number in action output

### ISSUE THREAD

**Issue by jonrohan** [changesets/action#82]
👋🏻 Hi I would like to have the `pull_number` in the `steps.changesets.outputs.pull_number` output from the action step if `steps.changesets.outputs.published == "false"`. 

This is so I can have my action also post a status on the pull request after the changesets/action step runs. 

https://github.com/changesets/action/blob/aacbc223926b9a6ac55d5922b90fd2a09e1fcfa9/src/run.ts#L274-L291

**Comment by Andarist** [comment]
Seems reasonable - I'm open for accepting a PR for this.
