### ISSUE TITLE
Skip createRelease

### ISSUE THREAD

**Issue by juanpicado** [changesets/action#87]
I'd like to avoid create GitHub releases, I have several packages in non production mode using alpha mode, every time I merge creates a lot of noise on my watchers. I've checked the code and I could not find any option, seems like goes as long publish the package.

I'm using it here https://github.com/verdaccio/verdaccio

It's related with https://github.com/changesets/action/issues/49

Base in your opinion, I'd be willing to work on it.

**Comment by Andarist** [comment]
Do you want to skip releases altogether or do you want to filter them so only for some the releases would be created?

**Comment by juanpicado** [comment]
I'd like be able skip all of them, to make it more simpler.

**Comment by akphi** [comment]
Hi, could we revisit this? I would be willing to help with this as well.

**Comment by akphi** [comment]
@Andarist this should be closed by https://github.com/changesets/action/pull/130
