### ISSUE TITLE
When local `.npmrc` is found the action still says `No .npmrc file found, creating one`

### ISSUE THREAD

**Issue by kamleshchandnani** [changesets/action#89]
Here's [the repo](https://github.com/kamleshchandnani/changesets-demo) where I have local `.npmrc` which is being considered but the changesets action still says. 
> No `.npmrc` file found, creating one

Here's the [output message from running action](https://github.com/kamleshchandnani/changesets-demo/runs/2493113514?check_suite_focus=true#step:5:16)

I got confused that it isn't picking up local my `.npmrc` even though it is. I think the messaging can be bit more contextual if it finds my local `.npmrc`. So I think we can change the messaging a bit.

**Comment by zthxxx** [comment]
+1

**Comment by Andarist** [comment]
@zthxxx I believe that the issue was addressed some time ago. Please take a look at my comment [here](https://github.com/changesets/action/pull/90#issuecomment-1003703156). If you still believe there is an issue with the latest code then please open a new issue describing the actual and expected results.

**Comment by zthxxx** [comment]
Project [here](https://github.com/zthxxx/getrusage.js) has the `.npmrc`, but in [changsets/action step](https://github.com/zthxxx/getrusage.js/runs/4683968516?check_suite_focus=true) also say “not found”.

Action file is [release.yml](https://github.com/zthxxx/getrusage.js/blob/master/.github/workflows/release.yml#L40)

**Comment by Andarist** [comment]
This project has project-level `.npmrc` file - the log is about the lack of the user-level file.

**Comment by zthxxx** [comment]
> This project has project-level `.npmrc` file - the log is about the lack of the user-level file.

yes, I known that, just will make a little confused

**Comment by Andarist** [comment]
How would you phrase this message to be less confusing? I'm open to suggestions.

**Comment by zthxxx** [comment]
maybe log with prefix “user-level”?

**Comment by zthxxx** [comment]
> I believe that the issue was addressed some time ago. Please take a look at my comment [here](https://github.com/changesets/action/pull/90#issuecomment-1003703156). If you still believe there is an issue with the latest code then please open a new issue describing the actual and expected results.

@Andarist I have opened a new issue #132 that relate to this issue with more deeper reason.

**Comment by elyobo** [comment]
> How would you phrase this message to be less confusing? I'm open to suggestions.

If there's a project level `.npmrc` present then I would skip logging and creating the user level file, as AFAIK it's redundant and so the log makes it appear that something is wrong when it's probably fine.
