### ISSUE TITLE
Defer NPM publish until PR merged

### ISSUE THREAD

**Issue by harrysolovay** [changesets/action#9]
It appears that the changes PR-auto-submission & NPM publish happen simultaneously... there're some quirks that I'm struggling to figure out. I was wondering if anyone had advice for getting this workflow working properly:

1. make changes in feature branch, add changes to staging, trigger `yarn changeset`, push to feature branch.
2. feature branch action composes changes (since the last version from master). That generated changelog gets PRed to master.
3. merging the PR into master triggers build task(s), version bump(s), NPM publish(es), and then gets the release tags to be reflected in the repo's `releases` section.

Is this setup possible with this action?

**Comment by harrysolovay** [comment]
I just wanted to ping this chat again. Anyone have thoughts on this?

**Comment by mitchellhamilton** [comment]
Sorry, I think I missed this

The creation of the PR and NPM publish don't happen simultaneously. The way this works is that if there are changesets on master, the version PR will be opened/updated and if there are no changesets on master, packages are published to npm.

We're thinking of adding another mode to this action that would do the versioning and publishing at the same time which I think is what you want?

**Comment by harrysolovay** [comment]
@mitchellhamilton yes, that would be great too!

What I described above though,––the ability to trigger a PR from a feature branch to the master branch, and then do the publish upon the merge––probably isn't a good workflow. Automating the PR to master means not being able to select draft mode, and could confuse others looking at master. I'm wondering if I had it all wrong. Is this the intended workflow?:

1. (like above) make changes in feature branch, add changes to staging, trigger `yarn changeset`, push to feature branch.
2. feature branch action composes changes (since the last version from master). That generated changelog gets PRed to **the feature branch** (and merged at the developer's discretion).
3. The developer manually opens a PR from the feature branch to the master branch.
4. Upon the PR's merge, an action kicks off the build task(s), version bump(s), NPM publish(es), and then gets the release tags to be reflected in the repo's `releases` section.

**Comment by mitchellhamilton** [comment]
The intended workflow is more like this:
1. Make changes in feature branch, trigger `yarn changeset`, push to feature branch
2. Open a PR to master/the default branch from the feature branch with the changes and changeset(s) and merge it
3. The action opens a PR which versions the packages and updates the changelogs based on the changesets
4. Upon the merge of the version PR, the action kicks off the build task(s), NPM publish(es), and then gets the release tags to be reflected in the repo's `releases` section.

**Comment by harrysolovay** [comment]
Okay––so the master branch is the only branch whose action actually combines the changesets. This absolutely sounds like the right workflow. I'll give this another go tonight & let you know how it goes (and then close this out) 👍 thank you @mitchellhamilton

**Comment by harrysolovay** [comment]
@mitchellhamilton I managed to get everything working in [this public repo](https://github.com/harrysolovay/testing-changesets) :) I see that the changeset-action-generated branch `changeset-release/some-feature` isn't deleted upon being merged back into `feature`. It would be awesome if there were a third action that could identify that merge event and take care of the cleanup (delete the generated branch).

I'm so loving this workflow. Much better than alternative JS monorepo workflows  💯

**Comment by mitchellhamilton** [comment]
I'd recommend using the GitHub option to do that https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches

**Comment by harrysolovay** [comment]
B E A U T I F U L . Thank you again!
