### ISSUE TITLE
Commit using the env `GITHUB_TOKEN`

### ISSUE THREAD

**Issue by br0p0p** [changesets/action#96]
Hi!

Would it be possible to make the "Version Packages" commit using the `GITHUB_TOKEN` env var? I would like PR workflows to be triggered on this PR but since the commit is made by the github actions bot, workflows aren't triggered (because of Github's rule that "workflows can't trigger other workflows") unless I add a commit manually.

If this action used the GITHUB_TOKEN env var to commit the version bump, it would be possible to set the env var to a bot user token and the workflows would then be triggered on the PR (because the PR and commit come from a user account, not an action) without a manual step.

I looked around in the code to see if this was a straightforward change but it wasn't obvious to me. I'd be happy to make this change if it is doable and you think it's a worthwhile change but I wanted to get some feedback on the idea before diving in.

**Comment by gregoralbrecht** [comment]
@br0p0p I also stumbled over this. Could you not pass a personal/a bot's token like this?
```yml
- name: Create Release Pull Request
  uses: changesets/action@master
  env:
    GITHUB_TOKEN: ${{ PERSONAL_TOKEN }}
```
Curious to hear if you've tried that :)
