### ISSUE TITLE
Documentation suggesting `fetch-depth: 0` is out of date

### ISSUE THREAD

**Issue by RoystonS** [changesets/action#97]
The documentation for the action currently suggests this for the configuration:

>  # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
>           fetch-depth: 0
> 

This is no longer necessary: the tool will automatically deepen shallow clones as necessary since https://github.com/atlassian/changesets/pull/495.

**Comment by Andarist** [comment]
That is true - would you like to prepare a documentation change for this?
