### ISSUE TITLE
E404 Not Found - PUT for published packages

### ISSUE THREAD

**Issue by talentlessguy** [changesets/action#98]
I'm using changesets github action to publish packages after running changesets version locally.

This is what I have in my github actions:

```
- name: Create Release Pull Request or Publish to npm
  id: changesets
  uses: changesets/action@master
  with:
    # This expects you to have a script called release which does a build for your packages and calls changeset publish
    publish: pnpm release
    commit: "chore: release"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

this is what I get in [actions logs](https://github.com/tinyhttp/tinyhttp/runs/3011980371#step:8:293):

```
🦋  error an error occurred while publishing @tinyhttp/ip-filter: E404 Not Found - PUT https://registry.npmjs.org/@tinyhttp%2fip-filter - Not found 
🦋  error 
🦋  error  '@tinyhttp/ip-filter@1.3.12' is not in the npm registry.
🦋  error You should bug the author to publish it (or use the name yourself!)
🦋  error 
🦋  error Note that you can also install from a
🦋  error tarball, folder, http url, or git url.
🦋  error an error occurred while publishing @tinyhttp/app: E404 Not Found - PUT https://registry.npmjs.org/@tinyhttp%2fapp - Not found 
🦋  error 
🦋  error  '@tinyhttp/app@1.3.12' is not in the npm registry.
🦋  error You should bug the author to publish it (or use the name yourself!)
🦋  error 
🦋  error Note that you can also install from a
🦋  error tarball, folder, http url, or git url.
🦋  error an error occurred while publishing @tinyhttp/unless: E404 Not Found - PUT https://registry.npmjs.org/@tinyhttp%2funless - Not found 
🦋  error 
🦋  error  '@tinyhttp/unless@1.3.12' is not in the npm registry.
🦋  error You should bug the author to publish it (or use the name yourself!)
🦋  error 
🦋  error Note that you can also install from a
🦋  error tarball, folder, http url, or git url.
🦋  error packages failed to publish:
🦋  @tinyhttp/app@1.3.12
🦋  @tinyhttp/ip-filter@1.3.12
🦋  @tinyhttp/unless@1.3.12
 ERROR  Command failed with exit code 1.
Error: The process '/home/runner/setup-pnpm/node_modules/.bin/pnpm' failed with exit code 1
    at a._setResult (/home/runner/work/_actions/changesets/action/master/dist/index.js:86:6638)
Error: The process '/home/runner/setup-pnpm/node_modules/.bin/pnpm' failed with exit code 1
    at a.CheckComplete (/home/runner/work/_actions/changesets/action/master/dist/index.js:86:6068)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/changesets/action/master/dist/index.js:86:5102)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

When I run `pnpm release` locally, it runs just fine

**Comment by zuhair-naqvi** [comment]
Same here, any updates on this?

**Comment by zuhair-naqvi** [comment]
Found the answer:

1. You need to ensure you create an environment, add your NPM_TOKEN as a secret to that environment, set `environment: YOUR_ENV_NAME` in your release workflow.

2. Add the following step before changesets action:
3.

**Comment by estrattonbailey** [comment]
+1, seeing the same issue. Creating an `.npmrc` as suggested here (and elsewhere) hasn't worked for me, unfortunately.

Afaict, the main outlier between my use case (and talentlessguy's) is usage of `pnpm` for dependencies. Could that be the culprit?

**Comment by estrattonbailey** [comment]
Just following up: I was able to get this working.

I had tried a few methods of creating an `.npmrc` on the fly a while back, but either it truly didn't work or I messed something up. Anyway, finally got back to this and noticed that pnpm [updated their docs](https://pnpm.io/using-changesets) for usage with Changesets, so I gave it another go.

I ended up creating and commiting an `.npmrc` to my repo, as [per pnpm docs](https://pnpm.io/npmrc#url_authtoken):

```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```

**However, this may be a real bug in the Changesets action**, since the README here states that it outputs a `.npmrc` file. I tested this and saw that it doesn't work unless I create an `.npmrc` myself.
- worked at [this commit](https://github.com/sure-thing/presta/actions/runs/1223066016)
- [failed again](https://github.com/sure-thing/presta/runs/3572214938?check_suite_focus=true#step:12:52) after removing `.npmrc`
- added `.npmrc` back, [works](https://github.com/sure-thing/presta/actions/runs/1223087595)

Here's essentially [the workflow I ended up with](https://github.com/sure-thing/presta/blob/main/.github/workflows/cd.yml) (including `.npmrc` in the root):

```yaml
name: CD

on:
  push:
    branches:
      - main

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      # env stuff
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: node - setup
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # pnpm stuff
      - name: pnpm - install
        run: npm i pnpm@latest -g
      - name: pnpm - config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: pnpm - install
        run: pnpm install

      # build
      - name: build
        run: pnpm build

      # publish to npm
      - name: release
        id: changesets
        uses: changesets/action@master
        with:
          publish: pnpm release
          version: pnpm version-packages
          commit: 'chore: version packages'
          title: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by estrattonbailey** [comment]
Ah, you're right, I totally missed that log. It's probably pnpm creating one with `pnpm config set`, which must shadow `npm config set`.

**Comment by Andarist** [comment]
I've created a PR that, hopefully, should help with this problem: https://github.com/changesets/action/pull/110

**Comment by Andarist** [comment]
The improvement from the commit above has landed. This should fix the @estrattonbailey's problem and hopefully, it should also fix the OP's problem.

If you bump into any more issues - please open a new thread with a repro case.

**Comment by nhhockeyplayer** [comment]
well yeah... someone forgot to fix the manual terminal command line way

this is the worst implementation I have ever seen

```
npm notice Publishing to https://npm.pkg.github.com/
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://npm.pkg.github.com/@meanstacknh%2fshared-root-ui-styles - The expected resource was not found.
npm ERR! 404 
npm ERR! 404  '@meanstacknh/shared-root-ui-styles@0.0.0' is not in this registry.
```

**Comment by vaynevayne** [comment]
hello, excuse me,   When executing locally, you need a npmToken in npmrc, right?
If I don't have a npmToken, can I do npm login -> changget push?

**Comment by hyunbinseo** [comment]
I fixed it by providing `NODE_AUTH_TOKEN` in the CI:

```yml
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: node --run ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # added
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
```

Reference:

- https://stackoverflow.com/a/75871670
- https://github.com/meilisearch/meilisearch-js-plugins/pull/983

**Comment by Fart10** [comment]
Thank you 🙏

**Comment by ashuvssut** [comment]
> fixed it by providing NODE_AUTH_TOKEN in the CI:

Only @hyunbinseo's solution worked for me
